### ISSUE TITLE
关于 sm2_verify 函数必须传入 私钥问题

### ISSUE THREAD

**Issue by lusi1990** [yetsing/gmssl_pyx#1]
你好,这个包比gmssl-python好用多了. 
不过使用过程用到一点问题.
因为 sm2_verify 验签只需要 公钥, 但是函数还必须传入私钥, 有时候私钥是拿不到的, 这个该如何解决呢?

**Comment by yetsing** [comment]
研究了一下，可以不传私钥
我改一下 api

**Comment by yetsing** [comment]
[v2.0.0](https://github.com/yetsing/gmssl_pyx/releases/tag/v2.0.0) 移除了私钥参数
